### PR TITLE
Refactor code to improve modularity and readability

### PR DESCRIPTION
**Pull request by DanielTea**
This commit includes several changes to the codebase to make it more modular and easier to maintain:

- Separated the code into multiple modules, including agents, locations, and text_generation.
- Reorganized the folder structure to follow best practices.
- Added new print and log variables to control output.
- Implemented a function to summarize the simulation output using OpenAI's GPT-4 API.
- Added functionality to load the OpenAI API key from a .env file.
- Updated the simulation loop to write its output to a log file.
- Improved the readability of the code by adding comments and spacing.

Overall, these changes make the code more modular, easier to understand, and easier to maintain.

### CODE REVIEW

**Comment by mkturkcan** [comment]
This is very useful! Just needs some minor changes:
- We don't want to have a closed-source, expensive API like GPT3/4 as the default generator since these models require a large number of evaluations. Ideally, it needs to be a choice between a local model and API calls.
- Keeping the networkx-based town graph would be ideal for determining where agents can go to.

**Comment by DanielTea** [comment]
Hey! Thanks mate! 

Yeah, you’re got a point here! I implemented the openai solution cause I didn’t had enough capacity on my laptop to run the llm mode locally, and no colab pro, so I’m going to implement the local version too, tomorrow, at least as far as you can choose. 

About the town graph, I oversaw that, should be reimplemented!

**Comment by DanielTea** [comment]
- Added the world_graph for simulation and made it loop over repeat simulations

- Updated generate function to allow for choosing between OpenAI and Hugging Face models

- Did not test the Hugging Face model switch

**Comment by mkturkcan** [comment]
I like how it looks right now. I'll test it and then merge.

**Pull request merged**
